window.DASHBOARD_DATA = {
  "generatedAt": "2026-06-16 09:36:05 UTC",
  "sourceUrl": "https://acnn1zogjo15.feishu.cn/sheets/Roissuv9qhKUHfttTXzcwX3QnVd",
  "revision": 234,
  "weekHeaders": [
    "W1\n6/9",
    "W2\n6/16",
    "W3\n6/23",
    "W4\n6/30",
    "W5\n7/7",
    "W6\n7/14",
    "W7\n7/21",
    "W8\n7/28",
    "W9\n8/4",
    "W10\n8/11",
    "W11\n8/18",
    "W12\n8/25",
    "W13\n9/1",
    "W14\n9/8",
    "W15\n9/15"
  ],
  "tasks": [
    {
      "id": "T01",
      "row": 6,
      "stage": "Pre-train",
      "task": "Github 代码下载与汇总",
      "owner": "朱君",
      "status": "进行中",
      "start": "2026-06-09",
      "end": "2026-06-20",
      "notes": "Github 下载，1~1.2T tokens",
      "weeks": [
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 12,
      "dependencies": [
        "T02"
      ]
    },
    {
      "id": "T02",
      "row": 7,
      "stage": "Pre-train",
      "task": "Github 下载进度与质量确认",
      "owner": "朱君",
      "status": "等待确认",
      "start": "2026-06-12",
      "end": "2026-06-20",
      "notes": "依赖 Github 下载；确认 star 分段进度",
      "weeks": [
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 9,
      "dependencies": [
        "T01"
      ]
    },
    {
      "id": "T03",
      "row": 8,
      "stage": "Pre-train",
      "task": "0~5 star 仓库格式化与精准去重",
      "owner": "宋磊",
      "status": "等待上游",
      "start": "2026-06-09",
      "end": "2026-06-16",
      "notes": "依赖 Github 下载；AWS 格式化 + 去重",
      "weeks": [
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 8,
      "dependencies": [
        "T01",
        "T02"
      ]
    },
    {
      "id": "T04",
      "row": 9,
      "stage": "Pre-train",
      "task": "Software Heritage / 其他 forge 补充评估",
      "owner": "TBD",
      "status": "待办",
      "start": "2026-06-30",
      "end": "2026-07-18",
      "notes": "放到 Github 之后；100~200B tokens",
      "weeks": [
        "",
        "",
        "",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 19,
      "dependencies": []
    },
    {
      "id": "T05",
      "row": 10,
      "stage": "Pre-train",
      "task": "从 Github 拉回 ipynb",
      "owner": "TBD",
      "status": "等待上游",
      "start": "2026-06-16",
      "end": "2026-07-03",
      "notes": "依赖 Github 下载完成",
      "weeks": [
        "",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 18,
      "dependencies": [
        "T01",
        "T02"
      ]
    },
    {
      "id": "T06",
      "row": 11,
      "stage": "Pre-train",
      "task": "Kaggle Notebook 数据源确认",
      "owner": "TBD",
      "status": "待办",
      "start": "2026-06-09",
      "end": "2026-06-12",
      "notes": "确认开源数据 / 彪哥数据；应该已经下载了",
      "weeks": [
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 4,
      "dependencies": []
    },
    {
      "id": "T07",
      "row": 12,
      "stage": "Pre-train",
      "task": "Jupyter / Kaggle Notebook 数据入湖",
      "owner": "TBD",
      "status": "待办",
      "start": "2026-06-30",
      "end": "2026-07-18",
      "notes": "依赖 ipynb + Kaggle 数据源",
      "weeks": [
        "",
        "",
        "",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 19,
      "dependencies": [
        "T05",
        "T06"
      ]
    },
    {
      "id": "T08",
      "row": 13,
      "stage": "Pre-train",
      "task": "高质量仓库优先筛选 >=5 stars",
      "owner": "宋磊",
      "status": "已完成",
      "start": "2026-06-09",
      "end": "2026-06-12",
      "notes": "动态开发数据上游",
      "weeks": [
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 4,
      "dependencies": [
        "T09",
        "T10",
        "T11"
      ]
    },
    {
      "id": "T09",
      "row": 14,
      "stage": "Pre-train",
      "task": "Natural diff patch 数据",
      "owner": "杨骁",
      "status": "已完成",
      "start": "2026-06-16",
      "end": "2026-07-03",
      "notes": "依赖高质量仓库筛选",
      "weeks": [
        "",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 18,
      "dependencies": [
        "T08"
      ]
    },
    {
      "id": "T10",
      "row": 15,
      "stage": "Pre-train",
      "task": "Commit packs 数据",
      "owner": "杨骁",
      "status": "已完成",
      "start": "2026-06-18",
      "end": "2026-07-03",
      "notes": "依赖高质量仓库筛选",
      "weeks": [
        "",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 16,
      "dependencies": [
        "T08"
      ]
    },
    {
      "id": "T11",
      "row": 16,
      "stage": "Pre-train",
      "task": "更多开发轨迹数据",
      "owner": "王培东",
      "status": "进行中",
      "start": "2026-06-16",
      "end": "2026-07-10",
      "notes": "不在P R中的commit / 多 PR / review 数据",
      "weeks": [
        "",
        "■■",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 25,
      "dependencies": []
    },
    {
      "id": "T12",
      "row": 17,
      "stage": "Pre-train",
      "task": "PR 筛选方法调研",
      "owner": "TBD",
      "status": "待办",
      "start": "2026-06-30",
      "end": "2026-07-18",
      "notes": "依赖动态开发数据初版",
      "weeks": [
        "",
        "",
        "",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 19,
      "dependencies": [
        "T09",
        "T10",
        "T11"
      ]
    },
    {
      "id": "T13",
      "row": 18,
      "stage": "Pre-train",
      "task": "Contextually-native trajectories",
      "owner": "孙诗昭",
      "status": "进行中",
      "start": "2026-07-14",
      "end": "2026-08-07",
      "notes": "依赖 PR 筛选调研",
      "weeks": [
        "",
        "",
        "",
        "",
        "",
        "■■",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 25,
      "dependencies": [
        "T12"
      ]
    },
    {
      "id": "T14",
      "row": 19,
      "stage": "Pre-train",
      "task": "Developer view 与 comments 组织",
      "owner": "TBD",
      "status": "待办",
      "start": "2026-07-14",
      "end": "2026-07-31",
      "notes": "依赖 PR 筛选调研",
      "weeks": [
        "",
        "",
        "",
        "",
        "",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 18,
      "dependencies": [
        "T12"
      ]
    },
    {
      "id": "T15",
      "row": 20,
      "stage": "Pre-train",
      "task": "Common Crawl programming pages 召回",
      "owner": "TBD",
      "status": "已完成",
      "start": "2026-06-09",
      "end": "2026-06-09",
      "notes": "已打分完成",
      "weeks": [
        "●",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 1,
      "dependencies": []
    },
    {
      "id": "T16",
      "row": 21,
      "stage": "Pre-train",
      "task": "Literature OCR pipeline",
      "owner": "汪元喆",
      "status": "进行中",
      "start": "2026-06-09",
      "end": "2026-07-31",
      "notes": "OCR 预计 7 月底完成",
      "weeks": [
        "■■",
        "■■",
        "■■",
        "■■",
        "■■",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 53,
      "dependencies": []
    },
    {
      "id": "T17",
      "row": 22,
      "stage": "Pre-train",
      "task": "PDF / literature code snippets 召回",
      "owner": "汪元喆",
      "status": "阻塞",
      "start": "2026-07-28",
      "end": "2026-08-14",
      "notes": "依赖 OCR 完成",
      "weeks": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 18,
      "dependencies": [
        "T16"
      ]
    },
    {
      "id": "T18",
      "row": 23,
      "stage": "Pre-train",
      "task": "Repo-level / long-context 输入格式改造",
      "owner": "汪元喆",
      "status": "待办",
      "start": "2026-08-11",
      "end": "2026-08-28",
      "notes": "依赖 PDF OCR code snippets",
      "weeks": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "■■",
        "■■",
        "■■",
        "",
        "",
        ""
      ],
      "durationDays": 18,
      "dependencies": [
        "T16",
        "T17"
      ]
    },
    {
      "id": "T19",
      "row": 24,
      "stage": "Governance",
      "task": "Decontamination",
      "owner": "骆煦芳",
      "status": "待办",
      "start": "2026-06-09",
      "end": "2026-06-26",
      "notes": "Benchmark repo / RL repos，可能前置",
      "weeks": [
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 18,
      "dependencies": []
    },
    {
      "id": "T20",
      "row": 25,
      "stage": "Governance",
      "task": "模型自我认同",
      "owner": "TBD",
      "status": "待办",
      "start": "2026-06-23",
      "end": "2026-07-03",
      "notes": "等开始训练前所有数据一起处理",
      "weeks": [
        "",
        "",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 11,
      "dependencies": []
    },
    {
      "id": "T21",
      "row": 26,
      "stage": "Governance",
      "task": "质量打分模型 pipeline",
      "owner": "王金予",
      "status": "进行中",
      "start": "2026-06-09",
      "end": "2026-07-10",
      "notes": "标注 / 训练 / 接入 data pipeline",
      "weeks": [
        "■■",
        "■■",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 32,
      "dependencies": []
    },
    {
      "id": "T22",
      "row": 27,
      "stage": "Pre-train",
      "task": "File-level / repo-level FIM",
      "owner": "刘仁彪",
      "status": "进行中",
      "start": "2026-06-16",
      "end": "2026-07-10",
      "notes": "依赖 Github 数据确认",
      "weeks": [
        "",
        "■■",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 25,
      "dependencies": [
        "T02"
      ]
    },
    {
      "id": "T23",
      "row": 28,
      "stage": "Governance",
      "task": "数据组织格式",
      "owner": "TBD",
      "status": "待办",
      "start": "2026-07-07",
      "end": "2026-07-24",
      "notes": "文件 / PR diff；先按 markdown；",
      "weeks": [
        "",
        "",
        "",
        "",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 18,
      "dependencies": []
    },
    {
      "id": "T24",
      "row": 29,
      "stage": "Mid-train",
      "task": "Synthetic Single-turn QA",
      "owner": "宋磊",
      "status": "进行中",
      "start": "2026-06-01",
      "end": "2026-06-20",
      "notes": "依赖 CC 召回 + 打分模型； 目标：66 M条QA",
      "weeks": [
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 20,
      "dependencies": [
        "T15",
        "T21"
      ]
    },
    {
      "id": "T25",
      "row": 30,
      "stage": "Mid-train",
      "task": "CC programming pages rewrite / normalize",
      "owner": "刘宇桓",
      "status": "进行中",
      "start": "2026-06-16",
      "end": "2026-07-17",
      "notes": "依赖 CC programming pages",
      "weeks": [
        "",
        "■■",
        "■■",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 32,
      "dependencies": [
        "T15"
      ]
    },
    {
      "id": "T26",
      "row": 31,
      "stage": "Mid-train",
      "task": "现有合成数据整理",
      "owner": "TBD",
      "status": "待办",
      "start": "2026-06-09",
      "end": "2026-06-20",
      "notes": "",
      "weeks": [
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 12,
      "dependencies": []
    },
    {
      "id": "T27",
      "row": 32,
      "stage": "Mid-train",
      "task": "Rewrite 数据混合实验",
      "owner": "宋磊",
      "status": "待办",
      "start": "2026-06-15",
      "end": "2026-06-22",
      "notes": "依赖 rewrite / normalize",
      "weeks": [
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 8,
      "dependencies": []
    },
    {
      "id": "T28",
      "row": 33,
      "stage": "Mid-train",
      "task": "Mid-train FIM 数据方案",
      "owner": "TBD",
      "status": "待办",
      "start": "2026-07-07",
      "end": "2026-07-31",
      "notes": "依赖 pretrain FIM",
      "weeks": [
        "",
        "",
        "",
        "",
        "■■",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 25,
      "dependencies": [
        "T22"
      ]
    },
    {
      "id": "T29",
      "row": 34,
      "stage": "Mid-train",
      "task": "Contextually-native trajectories 放入 mid-train",
      "owner": "孙诗昭",
      "status": "待办",
      "start": "2026-08-04",
      "end": "2026-08-21",
      "notes": "依赖 pretrain trajectories",
      "weeks": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 18,
      "dependencies": [
        "T13"
      ]
    },
    {
      "id": "T30",
      "row": 35,
      "stage": "Mid-train",
      "task": "Reasoning QA",
      "owner": "TBD",
      "status": "待办",
      "start": "2026-08-04",
      "end": "2026-08-21",
      "notes": "依赖 Synthetic Single-turn QA",
      "weeks": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "■■",
        "■■",
        "■■",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 18,
      "dependencies": [
        "T24"
      ]
    },
    {
      "id": "T31",
      "row": 36,
      "stage": "Mid-train",
      "task": "Execution-free trajectory data",
      "owner": "TBD",
      "status": "pass",
      "start": "2026-06-09",
      "end": "2026-06-09",
      "notes": "源文档：先 pass",
      "weeks": [
        "●",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 1,
      "dependencies": []
    },
    {
      "id": "T32",
      "row": 37,
      "stage": "Post-train",
      "task": "Execution-based agentic trajectory",
      "owner": "杨叙",
      "status": "进行中",
      "start": "2026-08-18",
      "end": "2026-09-04",
      "notes": "SWE-bench；已有初版和 SFT 结果",
      "weeks": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "■■",
        "■■",
        "■■",
        "",
        ""
      ],
      "durationDays": 18,
      "dependencies": []
    },
    {
      "id": "T33",
      "row": 38,
      "stage": "Post-train",
      "task": "未涉及 domain 数据补齐",
      "owner": "TBD",
      "status": "待办",
      "start": "2026-08-18",
      "end": "2026-09-04",
      "notes": "Computer use / Web Dev / Text-to-SQL / Security / OJ",
      "weeks": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "■■",
        "■■",
        "■■",
        "",
        ""
      ],
      "durationDays": 18,
      "dependencies": []
    },
    {
      "id": "T34",
      "row": 39,
      "stage": "Post-train",
      "task": "Instruction Following Data",
      "owner": "宋磊",
      "status": "进行中",
      "start": "2026-06-16",
      "end": "2026-06-30",
      "notes": "Databricks Dolly 15k等",
      "weeks": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "durationDays": 15,
      "dependencies": []
    },
    {
      "id": "T35",
      "row": 40,
      "stage": "Governance",
      "task": "输出信息细粒度标注",
      "owner": "TBD",
      "status": "待办",
      "start": "2026-08-18",
      "end": "2026-09-04",
      "notes": "依赖打分模型 + agentic 结果",
      "weeks": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "■■",
        "■■",
        "■■",
        "",
        ""
      ],
      "durationDays": 18,
      "dependencies": [
        "T21",
        "T32"
      ]
    },
    {
      "id": "T36",
      "row": 41,
      "stage": "Next",
      "task": "2% CC tokens",
      "owner": "TBD",
      "status": "下版",
      "start": "2026-09-01",
      "end": "2026-09-18",
      "notes": "下一个版本再说",
      "weeks": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "■■",
        "■■",
        "■■"
      ],
      "durationDays": 18,
      "dependencies": []
    }
  ]
};
